spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
